[package]
name = "influx_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.8"
url = "2.2.2"
chrono = "0.4.19"
log = "0.4"